controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /authentication_token
    methods: ['POST']

app_eleve:
    path: /eleve/{id}
    controller: App\Controller\EleveController::index